"""initial schema: tickets, messages, actions, audit_log, policies

Revision ID: e3d45bf2b3bb
Revises: 
Create Date: 2026-03-03 13:51:53.333529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3d45bf2b3bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension for future embedding columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('refund_cap', 'reship_cap', 'approval_threshold', 'auto_resolve', 'escalation_rule', name='policy_type'), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_policies_active', 'policies', ['active'], unique=False)
    op.create_index('ix_policies_type', 'policies', ['type'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'chat', 'sms', 'whatsapp', 'voice', name='channel_type'), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'resolved', 'closed', 'escalated', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticket_priority'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('customer_email', sa.String(length=320), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_created_at', 'tickets', ['created_at'], unique=False)
    op.create_index('ix_tickets_customer_email', 'tickets', ['customer_email'], unique=False)
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('refund', 'reship', 'discount', 'cancel', name='action_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'executed', 'rejected', 'failed', name='action_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_status', 'actions', ['status'], unique=False)
    op.create_index('ix_actions_ticket_id', 'actions', ['ticket_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('ticket_created', 'ticket_resolved', 'ticket_escalated', 'ai_response', 'policy_check', 'action_requested', 'action_executed', 'action_rejected', 'human_override', name='event_type'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_index('ix_audit_log_ticket_id', 'audit_log', ['ticket_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'agent', 'ai', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_ticket_id', 'messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_ticket_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_audit_log_ticket_id', table_name='audit_log')
    op.drop_index('ix_audit_log_event_type', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_actions_ticket_id', table_name='actions')
    op.drop_index('ix_actions_status', table_name='actions')
    op.drop_table('actions')
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_index('ix_tickets_customer_email', table_name='tickets')
    op.drop_index('ix_tickets_created_at', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_policies_type', table_name='policies')
    op.drop_index('ix_policies_active', table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
